# Generated by Django 2.0.1 on 2018-01-16 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('department', models.CharField(default='', max_length=100)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('graduation', models.CharField(default='졸업', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='', max_length=100)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='resume/')),
                ('name', models.CharField(default='', max_length=30)),
                ('birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('role', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='new_resume.Experience')),
            ],
        ),
        migrations.CreateModel(
            name='SelfIntroduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_introductions', to='new_resume.PrivateInformation')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('proficiency', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=255)),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='new_resume.PrivateInformation')),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='new_resume.PrivateInformation'),
        ),
        migrations.AddField(
            model_name='education',
            name='information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='new_resume.PrivateInformation'),
        ),
    ]
