# Generated by Django 2.0.1 on 2018-01-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_resume', '0003_auto_20180116_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateinformation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
