# Generated by Django 2.0.1 on 2018-01-27 09:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_resume', '0006_auto_20180127_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='contents'),
        ),
    ]
